version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: cakephp-docker
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    environment:
      - DATABASE_URL=mysql://app:password@mysql/cakephp_docker?encoding=utf8&timezone=UTC&cacheMetadata=true
      - DATABASE_TEST_URL=mysql://app:password@mysql-test/cakephp_docker?encoding=utf8&timezone=UTC&cacheMetadata=true
      - DEBUG=true
      - APP_DEFAULT_LOCALE=nl_NL
      - APP_DEFAULT_TIMEZONE=Europe/Amsterdam
  mysql:
    image: mysql:5.7
    ports:
      - 23306:3306
    environment:
      MYSQL_DATABASE: cakephp_docker
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  mysql-test:
    image: mysql:5.7
    ports:
      - 23307:3306
    environment:
      MYSQL_DATABASE: cakephp_docker
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
